In [9]:

def square(i):
    for i in range(i):
        yield i**2
#square(10)
for res in square(10):
    print(res)

0
1
4
9
16
25
36
49
64
81


In [19]:
#a=input()
#b=input()
def add(a,b):
    return a+b
res =add(2,3)
print(res)

5


In [29]:
res=lambda a,b:a+b
print(res(2,3))

5


In [33]:
X=lambda a,b,c,d:(a**2)+b*c**d
print(X(3,4,5,6))

62509


In [37]:
y=lambda a,b,c:a*b*c
print(y(4,6,8))

192


In [51]:
def sample(a):
    def wrapper(b):
        b=b.upper()
        return a(b)
    return wrapper
@sample
def process(b):
    return b
res=process
print(res("Hello"))

HELLO


In [ ]:
import pandas as pd
a=[1,2,3,4,5,6,7,8]
na=["AA","BB","CC","DD","EE","FF","GG","HH"]
id=[12,76,85,96,94,93,85,96]
c={"class":a,"name":na,"ID":id}
df=pd.DataFr

In [5]:
def div(a,b):
    return a/b;
#a=input()
#b=input()
res=div(2,3)
print(res)

0.6666666666666666


In [7]:
def smart_dev(func):
    def inner(a,b):
        if b==0:
            print("Error:Cannot divide by zero")
            return 
        if a>b:
            a,b=b,a
        return func(a,b)
    return inner
@smart_dev


SyntaxError: incomplete input (220836436.py, line 10)

In [1]:
import pandas as pd
import numpy as np

In [3]:
dict1 = {'Customer_id':[1,2,3,4,5,6],'Product':['Oven','Oven','Oven','Television','Television','Television' ] }
df1 = pd.DataFrame(dict1)
df1

Customer_id     Product
0            1        Oven
1            2        Oven
2            3        Oven
3            4  Television
4            5  Television
5            6  Television

In [5]:
dict2 = {'Customer_id':[1,2,3,4,5,6],'State':['california','america','Oven','mexico','Tokyo','Turkey' ] }
df2 = pd.DataFrame(dict2)
df2

Customer_id       State
0            1  california
1            2     america
2            3        Oven
3            4      mexico
4            5       Tokyo
5            6      Turkey

In [7]:
inner_join_df=pd.merge(df1,df2,on='Customer_id',how='inner')
inner_join_df

Customer_id     Product       State
0            1        Oven  california
1            2        Oven     america
2            3        Oven        Oven
3            4  Television      mexico
4            5  Television       Tokyo
5            6  Television      Turkey

In [17]:
#loc on colunms
#iloc on rows

In [51]:
data = pd.DataFrame({
    'Brand': ['Maruti', 'Hyundai', 'Tata','Mahindra', 'Maruti', 'Hyundai','Renault', 'Tata', 'Maruti'],
    'Year': [2012, 2014, 2011, 2015, 2012,2016, 2014, 2018, 2019],
    'Kms Driven': [50000, 30000, 60000,25000, 10000, 46000,31000, 15000, 12000],
    'City': ['Gurgaon', 'Delhi', 'Mumbai','Delhi', 'Mumbai', 'Delhi','Mumbai', 'Chennai', 'Ghaziabad'],'Mileage': [28, 27, 25, 26, 28,29, 24, 21, 24]
})
display(data)

Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

In [27]:
import pandas as pd

# Define a dictionary containing employee data
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32]}

# Define a dictionary containing employee data
data2 = {'key': ['K1', 'K2', 'K3', 'K4'],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data1)
df1 = pd.DataFrame(data2)
df
df1

key    Address Qualification
0  K1     Nagpur         Btech
1  K2     Kanpur           B.A
2  K3  Allahabad          Bcom
3  K4    Kannuaj        B.hons

In [49]:
display(data.loc[(data.Brand=="Hyundai")&(data.Year==2014)])

Brand  Year  Kms Driven   City  Mileage
1  Hyundai  2014       30000  Delhi       27

In [55]:
list1=[1,2,3]
avg=sum(list1)/len(list1)
print(avg)

2.0


In [63]:
print(tuple("varshu"))
#print(list("varshitha"))print(set(list1)'''

('v', 'a', 'r', 's', 'h', 'u')


In [65]:
data.isnull()

Brand   Year  Kms Driven   City  Mileage
0  False  False       False  False    False
1  False  False       False  False    False
2  False  False       False  False    False
3  False  False       False  False    False
4  False  False       False  False    False
5  False  False       False  False    False
6  False  False       False  False    False
7  False  False       False  False    False
8  False  False       False  False    False

In [73]:
import numpy as np
array=np.arange(20).reshape(2,10)
print(array)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [77]:
print(np.argmax(array,axis=1))
print(np.argmax(array,axis=0))

[9 9]
[1 1 1 1 1 1 1 1 1 1]


In [83]:
import numpy as np
a=np.array(20)
print(a)


20
